name: Backend-Main-Pull-Request-Build-Test

# Controls when the workflow will run

on:
  pull_request :
    branches:
      - "main"
      - "feature/**"
      - "bugfix/**"
      - "refactor/**"

jobs:
  # This workflow contains a single job called "build"

  test: # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start
        run: |
          echo "\
            _____   U  ___ u  ____      U  ___ u    _       ____     __   __
           |_ \" _|   \\/\"_ \/ |  _\"\\      \\/\"_ \/U  /\"\\  uU |  _\"\\ u  \\ \\ / /
             | |     | | | |/| | | |     | | | | \\/ _ \\/  \\| |_) |/   \\ V /
            /| |\\.-,_| |_| |U| |_| |\\.-,_| |_| | / ___ \\   |  _ <    U_|\"|_u
           u |_|U \\_)-\\___/  |____/ u \\_)-\\___/ /_/   \\_\\  |_| \\_\\     |_|
           _// \\\\_     \\\\     |||_         \\\\    \\\\    >>  //   \\\\_.-,//|(_
          (__) (__)   (__)   (__)_)       (__)  (__)  (__)(__)  (__)\_) (__)"
        shell: bash

      - name: make application.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.TEST_YML }}" > ./application-prod.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: |
          cd ./
          chmod +x ./gradlew
        shell: bash

      - name: Grant execute permission for git
        run: git config --global --add safe.directory /home/ubuntu/saltit

      - name: Build with Gradle
        run: |
          cd ./
          ./gradlew clean build -x test
        shell: bash

      - name: Test with Gradle
        run: |
          cd ./
          ./gradlew test
